-- MySQL Script generated by MySQL Workbench
-- Sun Dec  4 20:23:28 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema GRA
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema GRA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GRA` DEFAULT CHARACTER SET utf8 ;
USE `GRA` ;

-- -----------------------------------------------------
-- Table `GRA`.`planeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GRA`.`planeta` (
  `idplaneta` INT NOT NULL,
  `galaxia` VARCHAR(45) NULL,
  `estrela` VARCHAR(45) NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idplaneta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GRA`.`racaAlienigena`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GRA`.`racaAlienigena` (
  `idRacaAlienigena` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `pacifica` TINYINT NULL,
  `planeta_idplaneta` INT NOT NULL,
  PRIMARY KEY (`idRacaAlienigena`),
  INDEX `fk_racaAlienigena_planeta1_idx` (`planeta_idplaneta` ASC) VISIBLE,
  CONSTRAINT `fk_racaAlienigena_planeta1`
    FOREIGN KEY (`planeta_idplaneta`)
    REFERENCES `GRA`.`planeta` (`idplaneta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GRA`.`tecnologia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GRA`.`tecnologia` (
  `idTecnologia` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `funcao` VARCHAR(45) NULL,
  `tempo_criacao` VARCHAR(45) NULL,
  PRIMARY KEY (`idTecnologia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GRA`.`objetivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GRA`.`objetivo` (
  `idObjetivo` INT NOT NULL,
  `objetivo` VARCHAR(45) NULL,
  `racaAlienigena_idRacaAlienigena` INT NOT NULL,
  INDEX `fk_objetivo_racaAlienigena1_idx` (`racaAlienigena_idRacaAlienigena` ASC) VISIBLE,
  PRIMARY KEY (`idObjetivo`),
  CONSTRAINT `fk_objetivo_racaAlienigena1`
    FOREIGN KEY (`racaAlienigena_idRacaAlienigena`)
    REFERENCES `GRA`.`racaAlienigena` (`idRacaAlienigena`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GRA`.`tecnologia_has_racaAlienigena`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GRA`.`tecnologia_has_racaAlienigena` (
  `tecnologia_idTecnologia` INT NOT NULL,
  `racaAlienigena_idRacaAlienigena` INT NOT NULL,
  PRIMARY KEY (`tecnologia_idTecnologia`, `racaAlienigena_idRacaAlienigena`),
  INDEX `fk_tecnologia_has_racaAlienigena_racaAlienigena1_idx` (`racaAlienigena_idRacaAlienigena` ASC) VISIBLE,
  INDEX `fk_tecnologia_has_racaAlienigena_tecnologia1_idx` (`tecnologia_idTecnologia` ASC) VISIBLE,
  CONSTRAINT `fk_tecnologia_has_racaAlienigena_tecnologia1`
    FOREIGN KEY (`tecnologia_idTecnologia`)
    REFERENCES `GRA`.`tecnologia` (`idTecnologia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tecnologia_has_racaAlienigena_racaAlienigena1`
    FOREIGN KEY (`racaAlienigena_idRacaAlienigena`)
    REFERENCES `GRA`.`racaAlienigena` (`idRacaAlienigena`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
